---
- name: PHP | DEBIAN | Add apt key
  apt_key:
    url: https://packages.sury.org/php/apt.gpg
    state: present

- name: PHP | DEBIAN | Add apt repo
  apt_repository:
    repo: "deb https://packages.sury.org/php/ {{ ansible_distribution_release }} main"
    update_cache: yes

